import { attachAutocomplete } from './geocode';
import { fetchReading } from './readingApi';
import { renderShareCardPNG } from './sharecard';
import { drawZodiacWheel } from './zodiac';
const byId=(id)=>document.getElementById(id);
function isoToGerman(input){if(!/^\d{4}-\d{2}-\d{2}$/.test(input))return input;const[y,m,d]=input.split('-');return`${d}.${m}.${y}`}
function approxMap(v){const map={morning:'morgens',noon:'mittags',evening:'abends',night:'nachts','':'unbekannt'};return map[v]??'unbekannt'}
function setStatus(m){byId('status').textContent=m}function setDebug(o){const b=byId('debug');const p=byId('debugPre');b.hidden=false;p.textContent=JSON.stringify(o,null,2)}
function stableSeed(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function readForm(){const dRaw=(byId('birthDate').value||'').trim();const p=(byId('birthPlace').value||'').trim();const lat=(byId('birthLat').value||'').trim();const lon=(byId('birthLon').value||'').trim();const t=(byId('birthTime').value||'').trim();const a=(byId('timeApprox').value||'').trim();const tf=(byId('timeFrame').value||'week').trim();const mode=(byId('mode').value||'balanced').trim();if(!dRaw||!p)throw new Error('Bitte Datum und Ort angeben.');const birthDate=/^\d{4}-\d{2}-\d{2}$/.test(dRaw)?isoToGerman(dRaw):dRaw;const payload={birthDate,birthPlace:p,period:tf,approxDaypart:approxMap(a),mode};if(t&&/^\d{1,2}:\d{2}$/.test(t))payload.birthTime=t;if(lat&&lon)payload.coords={lat:Number(lat),lon:Number(lon)};const seed=stableSeed((dRaw||'')+'|'+(p||''));payload.seed=seed;payload.tone=mode;return payload}
function permalinkFromForm(){const d=byId('birthDate').value;const p=byId('birthPlace').value;const t=byId('birthTime').value;const a=byId('timeApprox').value;const tf=byId('timeFrame').value;const lat=byId('birthLat').value;const lon=byId('birthLon').value;const mode=byId('mode').value;const seed=stableSeed((d||'')+'|'+(p||''));const u=new URL(location.href);u.searchParams.set('d',d);u.searchParams.set('p',p);if(t)u.searchParams.set('t',t);if(a)u.searchParams.set('a',a);if(tf)u.searchParams.set('tf',tf);if(lat&&lon){u.searchParams.set('lat',lat);u.searchParams.set('lon',lon)}u.searchParams.set('mode',mode);u.searchParams.set('seed',String(seed));byId('permalink').href=u.toString()}
async function onSubmit(e){e.preventDefault();try{setStatus('⏳ Berechnung läuft …');const payload=readForm();const data=await fetchReading(payload);setStatus('✓ Fertig');renderReading(data);byId('shareCardPreview').hidden=false;await drawShareCardFromReading(data);permalinkFromForm()}catch(err){setStatus('Fehler: '+(err?.message||String(err)));setDebug(err)}}
function renderReading(data){const out=byId('readingOut');out.innerHTML='';const make=(t,x)=>{const b=document.createElement('div');b.className='reading-block';b.innerHTML=`<strong>${t}</strong><div class="autocomplete-muted">${x}</div>`;out.appendChild(b)};if(data?.summary)make('Zusammenfassung',data.summary);if(data?.highlights?.length)make('Highlights',data.highlights.slice(0,5).map(s=>'• '+s).join('<br>'));if(data?.sections?.length)for(const s of data.sections)make(s.title||'Abschnitt',s.text||'');if(!out.children.length)make('Antwort',typeof data==='string'?data:JSON.stringify(data))}
async function drawShareCardFromReading(data){const canvas=byId('shareCanvas');const d=byId('birthDate').value;const p=byId('birthPlace').value;const tf=byId('timeFrame').value;const title='Dein Moment unter den Sternen';const bullets=(data?.highlights?.length?data.highlights.slice(0,3):(data?.sections||[]).slice(0,3).map(s=>s.title||'Impulse'));const png=await renderShareCardPNG(canvas,{title,subtitle:`${p} · ${d} · ${tf}`,bullets});const a=byId('btnDownload');a.href=png;a.hidden=false}
function attachEvents(){document.getElementById('astro-form').addEventListener('submit',onSubmit);document.getElementById('btnShare').addEventListener('click',async()=>{byId('shareCardPreview').hidden=false;await drawShareCardFromReading({highlights:['Atem holen. Fokus finden.','Kleiner mutiger Schritt.','Heute freundlich zu dir sein.']})})}
function hydrateFromURL(){const url=new URL(location.href);const map={d:'birthDate',p:'birthPlace',t:'birthTime',a:'timeApprox',tf:'timeFrame',mode:'mode',lat:'birthLat',lon:'birthLon'};for(const[q,id]of Object.entries(map)){const v=url.searchParams.get(q);if(v)document.getElementById(id).value=v}permalinkFromForm()}
function init(){drawZodiacWheel(document.getElementById('zodiac-canvas'));attachAutocomplete({input:document.getElementById('birthPlace'),menu:document.getElementById('place-suggest'),onPick(place){document.getElementById('birthPlace').value=place.label;document.getElementById('birthLat').value=String(place.lat??'');document.getElementById('birthLon').value=String(place.lon??'');permalinkFromForm()}});attachEvents();hydrateFromURL()}
document.addEventListener('DOMContentLoaded',init);
